// Code generated by go-swagger; DO NOT EDIT.

package arts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteArtPieceParams creates a new DeleteArtPieceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteArtPieceParams() *DeleteArtPieceParams {
	return &DeleteArtPieceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteArtPieceParamsWithTimeout creates a new DeleteArtPieceParams object
// with the ability to set a timeout on a request.
func NewDeleteArtPieceParamsWithTimeout(timeout time.Duration) *DeleteArtPieceParams {
	return &DeleteArtPieceParams{
		timeout: timeout,
	}
}

// NewDeleteArtPieceParamsWithContext creates a new DeleteArtPieceParams object
// with the ability to set a context for a request.
func NewDeleteArtPieceParamsWithContext(ctx context.Context) *DeleteArtPieceParams {
	return &DeleteArtPieceParams{
		Context: ctx,
	}
}

// NewDeleteArtPieceParamsWithHTTPClient creates a new DeleteArtPieceParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteArtPieceParamsWithHTTPClient(client *http.Client) *DeleteArtPieceParams {
	return &DeleteArtPieceParams{
		HTTPClient: client,
	}
}

/* DeleteArtPieceParams contains all the parameters to send to the API endpoint
   for the delete art piece operation.

   Typically these are written to a http.Request.
*/
type DeleteArtPieceParams struct {

	/* ID.

	   The id of the art piece for which the operation relates

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete art piece params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteArtPieceParams) WithDefaults() *DeleteArtPieceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete art piece params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteArtPieceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete art piece params
func (o *DeleteArtPieceParams) WithTimeout(timeout time.Duration) *DeleteArtPieceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete art piece params
func (o *DeleteArtPieceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete art piece params
func (o *DeleteArtPieceParams) WithContext(ctx context.Context) *DeleteArtPieceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete art piece params
func (o *DeleteArtPieceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete art piece params
func (o *DeleteArtPieceParams) WithHTTPClient(client *http.Client) *DeleteArtPieceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete art piece params
func (o *DeleteArtPieceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete art piece params
func (o *DeleteArtPieceParams) WithID(id int64) *DeleteArtPieceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete art piece params
func (o *DeleteArtPieceParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteArtPieceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
