// Code generated by go-swagger; DO NOT EDIT.

package arts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xiaolonggou/microservice/v1/sdk/models"
)

// UpdateArtPieceReader is a Reader for the UpdateArtPiece structure.
type UpdateArtPieceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateArtPieceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateArtPieceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateArtPieceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewUpdateArtPieceNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateArtPieceCreated creates a UpdateArtPieceCreated with default headers values
func NewUpdateArtPieceCreated() *UpdateArtPieceCreated {
	return &UpdateArtPieceCreated{}
}

/* UpdateArtPieceCreated describes a response with status code 201, with default header values.

No content is returned by this API endpoint
*/
type UpdateArtPieceCreated struct {
}

func (o *UpdateArtPieceCreated) Error() string {
	return fmt.Sprintf("[PUT /arts][%d] updateArtPieceCreated ", 201)
}

func (o *UpdateArtPieceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateArtPieceNotFound creates a UpdateArtPieceNotFound with default headers values
func NewUpdateArtPieceNotFound() *UpdateArtPieceNotFound {
	return &UpdateArtPieceNotFound{}
}

/* UpdateArtPieceNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type UpdateArtPieceNotFound struct {
	Payload *models.GenericError
}

func (o *UpdateArtPieceNotFound) Error() string {
	return fmt.Sprintf("[PUT /arts][%d] updateArtPieceNotFound  %+v", 404, o.Payload)
}
func (o *UpdateArtPieceNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateArtPieceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateArtPieceNotImplemented creates a UpdateArtPieceNotImplemented with default headers values
func NewUpdateArtPieceNotImplemented() *UpdateArtPieceNotImplemented {
	return &UpdateArtPieceNotImplemented{}
}

/* UpdateArtPieceNotImplemented describes a response with status code 501, with default header values.

Generic error message returned as a string
*/
type UpdateArtPieceNotImplemented struct {
	Payload *models.GenericError
}

func (o *UpdateArtPieceNotImplemented) Error() string {
	return fmt.Sprintf("[PUT /arts][%d] updateArtPieceNotImplemented  %+v", 501, o.Payload)
}
func (o *UpdateArtPieceNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateArtPieceNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
